export const migrationQueries = [
  `CREATE TABLE \`audit_logs\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`actor_id\` text,
	\`actor_type\` text DEFAULT 'system' NOT NULL,
	\`action\` text NOT NULL,
	\`entity_type\` text,
	\`entity_id\` text,
	\`severity\` text DEFAULT 'info' NOT NULL,
	\`message\` text NOT NULL,
	\`metadata\` text,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`audit_org_created_idx\` ON \`audit_logs\` (\`org_id\`,\`created_at\`)`,
  `CREATE INDEX \`audit_org_action_idx\` ON \`audit_logs\` (\`org_id\`,\`action\`)`,
  `CREATE TABLE \`configurations\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`key\` text NOT NULL,
	\`value\` text NOT NULL,
	\`description\` text,
	\`updated_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE UNIQUE INDEX \`config_org_key_idx\` ON \`configurations\` (\`org_id\`,\`key\`)`,
  `CREATE TABLE \`declarations\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`employee_id\` text NOT NULL,
	\`fiscal_year\` text NOT NULL,
	\`type\` text NOT NULL,
	\`amount\` real DEFAULT 0 NOT NULL,
	\`approved_amount\` real,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`proof_url\` text,
	\`reviewed_by\` text,
	\`reviewed_at\` integer,
	\`remarks\` text,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	\`updated_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`employee_id\`) REFERENCES \`employees\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`decl_org_emp_fy_idx\` ON \`declarations\` (\`org_id\`,\`employee_id\`,\`fiscal_year\`)`,
  `CREATE INDEX \`decl_org_status_idx\` ON \`declarations\` (\`org_id\`,\`status\`)`,
  `CREATE TABLE \`departments\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`code\` text,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`dept_org_idx\` ON \`departments\` (\`org_id\`)`,
  `CREATE UNIQUE INDEX \`dept_org_code_idx\` ON \`departments\` (\`org_id\`,\`code\`)`,
  `CREATE TABLE \`employees\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`department_id\` text,
	\`code\` text NOT NULL,
	\`first_name\` text NOT NULL,
	\`last_name\` text NOT NULL,
	\`email\` text,
	\`phone\` text,
	\`date_of_birth\` text,
	\`gender\` text,
	\`pan_number\` text,
	\`aadhaar_number\` text,
	\`pf_uan\` text,
	\`esi_number\` text,
	\`date_of_joining\` text,
	\`date_of_appointment\` text,
	\`date_of_resignation\` text,
	\`status\` text DEFAULT 'active' NOT NULL,
	\`basic_pay\` real DEFAULT 0 NOT NULL,
	\`da_percent\` real DEFAULT 0 NOT NULL,
	\`hra_percent\` real DEFAULT 0 NOT NULL,
	\`allowances\` text,
	\`bank_name\` text,
	\`bank_account\` text,
	\`bank_ifsc\` text,
	\`tax_regime\` text DEFAULT 'new' NOT NULL,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	\`updated_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`emp_org_dept_idx\` ON \`employees\` (\`org_id\`,\`department_id\`)`,
  `CREATE INDEX \`emp_org_status_idx\` ON \`employees\` (\`org_id\`,\`status\`)`,
  `CREATE UNIQUE INDEX \`emp_org_code_idx\` ON \`employees\` (\`org_id\`,\`code\`)`,
  `CREATE TABLE \`leave_records\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`employee_id\` text NOT NULL,
	\`type\` text NOT NULL,
	\`start_date\` text NOT NULL,
	\`end_date\` text NOT NULL,
	\`days\` real DEFAULT 0 NOT NULL,
	\`reason\` text,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`approved_by\` text,
	\`approved_at\` integer,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	\`updated_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`employee_id\`) REFERENCES \`employees\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`leave_org_emp_status_idx\` ON \`leave_records\` (\`org_id\`,\`employee_id\`,\`status\`)`,
  `CREATE INDEX \`leave_org_status_idx\` ON \`leave_records\` (\`org_id\`,\`status\`)`,
  `CREATE TABLE \`organizations\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`code\` text NOT NULL,
	\`address\` text,
	\`state_code\` text DEFAULT 'MH' NOT NULL,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL
)`,
  `CREATE UNIQUE INDEX \`org_code_idx\` ON \`organizations\` (\`code\`)`,
  `CREATE TABLE \`salary_records\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`org_id\` text NOT NULL,
	\`employee_id\` text NOT NULL,
	\`department_id\` text,
	\`month\` integer NOT NULL,
	\`year\` integer NOT NULL,
	\`status\` text DEFAULT 'draft' NOT NULL,
	\`basic_pay\` real DEFAULT 0 NOT NULL,
	\`da\` real DEFAULT 0 NOT NULL,
	\`hra\` real DEFAULT 0 NOT NULL,
	\`allowances\` text,
	\`gross_earnings\` real DEFAULT 0 NOT NULL,
	\`tds\` real DEFAULT 0 NOT NULL,
	\`pf_employee\` real DEFAULT 0 NOT NULL,
	\`pf_employer\` real DEFAULT 0 NOT NULL,
	\`pf_eps\` real DEFAULT 0 NOT NULL,
	\`esi_employee\` real DEFAULT 0 NOT NULL,
	\`esi_employer\` real DEFAULT 0 NOT NULL,
	\`professional_tax\` real DEFAULT 0 NOT NULL,
	\`total_deductions\` real DEFAULT 0 NOT NULL,
	\`net_pay\` real DEFAULT 0 NOT NULL,
	\`run_id\` text,
	\`frozen_at\` integer,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	\`updated_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`org_id\`) REFERENCES \`organizations\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`employee_id\`) REFERENCES \`employees\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON UPDATE no action ON DELETE no action
)`,
  `CREATE INDEX \`sr_org_month_year_idx\` ON \`salary_records\` (\`org_id\`,\`month\`,\`year\`)`,
  `CREATE INDEX \`sr_org_employee_idx\` ON \`salary_records\` (\`org_id\`,\`employee_id\`)`,
  `CREATE UNIQUE INDEX \`sr_org_emp_month_year_idx\` ON \`salary_records\` (\`org_id\`,\`employee_id\`,\`month\`,\`year\`)`,
]
